### ISSUE TITLE
Title of GitHub repo

### ISSUE THREAD

**Issue by andreaskring** [magenta-aps/alfresco-enable-clickble-links-in-preview-share#1]
@DarkStar1 We should probebly rename this repo to alfresco-enable-clickble-links-in-preview-share in order to follow the same convention as for the others Magenta Alfresco modules. Then it will pop up when searching for Alfresco modules on the Magenta GitHub main page.

**Comment by douglascrp** [comment]
@DarkStar1 You can close this, right?

**Comment by DarkStar1** [comment]
@douglascrp Yes
